# Generated by Django 4.0.2 on 2022-02-06 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=255)),
                ('section', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student Model',
                'ordering': ['-created_at'],
            },
        ),
    ]
